
version: 2

models:
  - name: filmes_by_genre
    description: ""
    columns:
      - name: count_films
        data_type: int64
        description: ""

      - name: avg_rat
        data_type: float64
        description: ""

      - name: avg_num_votes
        data_type: float64
        description: ""

      - name: genres
        data_type: string
        description: ""

      - name: startyear
        data_type: date
        description: ""

      - name: rn
        data_type: int64
        description: ""
