
version: 2

models:
  - name: rating_films
    description: ""
    columns:
      - name: avg_rating
        data_type: float64
        description: ""

      - name: avg_num_votes
        data_type: float64
        description: ""

      - name: startyear
        data_type: int64
        description: ""

      - name: genres
        data_type: string
        description: ""

  - name: number_films_by_genre
    description: ""
    columns:
      - name: count_films
        data_type: int64
        description: ""

      - name: avg_rat
        data_type: float64
        description: ""

      - name: genres
        data_type: string
        description: ""

      - name: startyear
        data_type: int64
        description: ""
