
version: 2

models:
  - name: common_data_imdb
    description: ""
    columns:
      - name: tconst
        data_type: string
        description: ""

      - name: titletype
        data_type: string
        description: ""

      - name: primarytitle
        data_type: string
        description: ""

      - name: originaltitle
        data_type: string
        description: ""

      - name: averagerating
        data_type: float64
        description: ""

      - name: isadult
        data_type: boolean
        description: ""

      - name: isadult_description
        data_type: string
        description: ""

      - name: startyear
        data_type: date
        description: ""

      - name: endyear
        data_type: date
        description: ""

      - name: runtimeminutes
        data_type: int64
        description: ""

      - name: genres
        data_type: string
        description: ""

      - name: numvotes
        data_type: int64
        description: ""

      - name: parenttconst
        data_type: string
        description: ""

      - name: seasonnumber
        data_type: int64
        description: ""

      - name: episodenumber
        data_type: int64
        description: ""

      - name: director
        data_type: string
        description: ""

      - name: director_name
        data_type: string
        description: ""

      - name: director_birthyear
        data_type: date
        description: ""

      - name: director_deathyear
        data_type: date
        description: ""

      - name: director_primaryprofession
        data_type: string
        description: ""

      - name: director_knownfortitles
        data_type: string
        description: ""

      - name: writer
        data_type: string
        description: ""

      - name: writer_name
        data_type: string
        description: ""

      - name: writer_birthyear
        data_type: date
        description: ""

      - name: writer_deathyear
        data_type: date
        description: ""

      - name: writer_primaryprofession
        data_type: string
        description: ""

      - name: writer_knownfortitles
        data_type: string
        description: ""

  - name: number_films_by_genre
    description: ""
    columns:
      - name: count_films
        data_type: int64
        description: ""

      - name: avg_rat
        data_type: float64
        description: ""

      - name: avg_num_votes
        data_type: float64
        description: ""

      - name: genres
        data_type: string
        description: ""

      - name: startyear
        data_type: date
        description: ""

      - name: rn
        data_type: int64
        description: ""

  - name: common_data_partitioned_by_date
    description: ""
    columns:
      - name: tconst
        data_type: string
        description: ""

      - name: titletype
        data_type: string
        description: ""

      - name: primarytitle
        data_type: string
        description: ""

      - name: originaltitle
        data_type: string
        description: ""

      - name: averagerating
        data_type: float64
        description: ""

      - name: isadult
        data_type: boolean
        description: ""

      - name: isadult_description
        data_type: string
        description: ""

      - name: startyear
        data_type: date
        description: ""

      - name: endyear
        data_type: date
        description: ""

      - name: runtimeminutes
        data_type: int64
        description: ""

      - name: genres
        data_type: string
        description: ""

      - name: numvotes
        data_type: int64
        description: ""

      - name: parenttconst
        data_type: string
        description: ""

      - name: seasonnumber
        data_type: int64
        description: ""

      - name: episodenumber
        data_type: int64
        description: ""

      - name: director
        data_type: string
        description: ""

      - name: director_name
        data_type: string
        description: ""

      - name: director_birthyear
        data_type: date
        description: ""

      - name: director_deathyear
        data_type: date
        description: ""

      - name: director_primaryprofession
        data_type: string
        description: ""

      - name: director_knownfortitles
        data_type: string
        description: ""

      - name: writer
        data_type: string
        description: ""

      - name: writer_name
        data_type: string
        description: ""

      - name: writer_birthyear
        data_type: date
        description: ""

      - name: writer_deathyear
        data_type: date
        description: ""

      - name: writer_primaryprofession
        data_type: string
        description: ""

      - name: writer_knownfortitles
        data_type: string
        description: ""
